version: "3"
services:
  python:
    build: ./python
    ports:
      - "8008:8888"
    stdin_open: true
    tty: true
    volumes:
      - ./python/scripts:/JupyterLab
  selenium:
    build: ./selenium
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
